apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  ports:
  - port: 1443
  selector:
    app: mssql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  hostname: mssqlinst
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/rhel/server:2019-latest
        name: mssql
        env:
          - name: ACCEPT_EULA
            value: 'Y'
        envFrom:
          - secretRef:
              name: mssql
        ports:
        - containerPort: 1443
          name: mssql
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/lib/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-pv-claim